### ISSUE TITLE
Automatic rescaling camera matrix on different resolution

### ISSUE THREAD

**Issue by okalachev** [OTL/cv_camera#10]
Currently, if the resolution of camera info doesn't match the actual `~image_width` and `~image_height`, `cv_camera` just ignores it (without any warnings). This can be confusing.

I propose automatic camera info rescaling (if appropriate parameter is enabled). It can be done with some code like this:

```c++
cameraMat.copyTo(scaledCameraMat);
widthCoeff = imageWidth / cameraInfoWidth;
heightCoeff = imageHeight / cameraInfoHeight;
scaledCameraMat.at<float>(0, 0) *= widthCoeff;
scaledCameraMat.at<float>(0, 2) *= widthCoeff;
scaledCameraMat.at<float>(1, 1) *= heightCoeff;
scaledCameraMat.at<float>(1, 2) *= heightCoeff;

newCamMat = cv::getOptimalNewCameraMatrix(scaledCameraMat, distCoeffs, currFrameSize, 1);
```

If the parameter is disabled, a warning can be thrown in such a situation.

**Comment by OTL** [comment]
PR is welcome, but your example code is not ROS style. Please read the rule in ROS site and understand the style.
