### ISSUE TITLE
 ‘CAP_V4L’ is not a member of ‘cv’

### ISSUE THREAD

**Issue by aissa360** [OTL/cv_camera#16]
Please I need help I am new to ros, I'm using ros indigo. I downloaded the package and when catkin_making it. it gives this errors message :  ‘CAP_V4L’ is not a member of ‘cv’ 
I did not change anything in CMakefile!

**Comment by OTL** [comment]
This repo is for kinetic now.
Indigo is super old release. You should stop to use indigo and use Kinetic if you are a beginner.

And why you want to build this by yourself, instead of binary release?
