### ISSUE TITLE
Build fails Opencv4

### ISSUE THREAD

**Issue by gclarke42** [OTL/cv_camera#25]
I am trying to build this on a jetson nano which comes installed with opencv4.  Trying to build this it looks like its trying to find /usr/include/opencv. Since my CV include path is /usr/include/opencv4 I tried making a symbolic link.  This allowed the code to find headers but generated a number of build errors so i assume this was built for CV3 instead.  Is there suppose to open CV 4? If so what do I need to do to correct my issue?

**Comment by OTL** [comment]
This PR(https://github.com/OTL/cv_camera/pull/28) might solve the problem.
Try to update.

**Comment by OTL** [comment]
I believe that this has been solved.
