### ISSUE TITLE
Build issue Raspberry Pi4

### ISSUE THREAD

**Issue by HaroldSP** [OTL/cv_camera#27]
Hi everyone!

Previously I have installed ROS and I tried to include cv_camera with the following commands:

    rosinstall_generator desktop teleop_twist_keyboard cv_camera --rosdistro melodic --deps --wet-only --tar > melodic-desktop-wet.rosinstall
    wstool init -j8 src melodic-desktop-wet.rosinstall
    rosdep install --from-paths src --ignore-src --rosdistro melodic -y
    cd && cd ~/ros_catkin_ws
    sudo ./src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --install-space /opt/ros/melodic -j4
    echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc

Building with cmake:
![image](https://user-images.githubusercontent.com/55085987/82688840-38afe100-9c62-11ea-9d9a-2c1c111dcb1f.png)

Tried to use rosdeb:
![image](https://user-images.githubusercontent.com/55085987/82689389-0e125800-9c63-11ea-8122-f30df69b528f.png)

Manually added cv_camera source:

    sudo cp -r ~/catkin_ws/src/cv_camera/ /opt/ros/melodic/share/
And still doesn't work and I don't know what to do.
![image](https://user-images.githubusercontent.com/55085987/82689535-4b76e580-9c63-11ea-8205-fd47c292b6fa.png)

Many thanks

UPD1:

It looks like there is a similar problem [here](https://stackoverflow.com/questions/56572665/opencv4-error-cv-cap-prop-frame-width-was-not-declared-in-this-scope).

**Comment by OTL** [comment]
This PR (https://github.com/OTL/cv_camera/pull/28) might solve your problem.
It has been merged already. Please try update!

**Comment by HaroldSP** [comment]
@OTL thanks! It helped.
