### ISSUE TITLE
Failing to set image width

### ISSUE THREAD

**Issue by vigneshrajap** [OTL/cv_camera#29]
I am using wide cameras  (ELP-USBFHD09DC-FD180) that outputs Full HD and HD resolution. However cv_camera fails to set to higher resolution.

It always gives warning "fail to set image_width" and publishes only at 640*480 image resolution.

```
<launch>

 <node pkg="cv_camera" name="camera_rear_left"  type="cv_camera_node" output="screen">
    <param name="frame_id" value="camera_rear_left" />
    <param name="device_path" value="/dev/camera_rear_left" />
    <param name="image_width" value="1280" />
    <param name="cv_cap_prop_fourcc" value="MJPG"/>
    <param name="image_height" value="720" />
 </node>

</launch>                                                                                                   
```

Any help is appreciated!

**Comment by OTL** [comment]
This package is thin wrapper of OpenCV video capture module.
Can you check if it is possible to do that from opencv?

**Comment by vigneshrajap** [comment]
So I found the problem is with the OpenCV version. OpenCV 2 version works well with the current cv_camera package. Whereas the OpenCV 3 versions have API changes, so the image width is not capturing now.

**Comment by Sunshengjin** [comment]
@vigneshrajap Hi, Vignesh. I'm using ROS Noetic on RaspiOS ,  I have the same issue .  Could you tell me which API you found is different  and how to use the correct API to set the image width.  Thanks alot!

**Comment by Sunshengjin** [comment]
In addition, I found that the OpenCV version corresponding to ROS Noetic in RasipiOS is 3.2. And In the OpenCV3.2 user manual, the image width  parameters are the same as those in this project code, see : 
![image](https://user-images.githubusercontent.com/25906092/103399711-52f95800-4b7d-11eb-85f3-eaa250217173.png)
![image](https://user-images.githubusercontent.com/25906092/103399734-6b697280-4b7d-11eb-9848-1770de1a77bf.png)

and when i running cv_camera_node, although the program shows fail to set image_width, but the resolution of the image data posted through the topic has been set correctly

**Comment by Sunshengjin** [comment]
In addition, I found that the OpenCV version corresponding to ROS Noetic in RasipiOS is 3.2. And In the OpenCV3.2 user manual, the image width parameters are the same as those in this project code, see : 
![image](https://user-images.githubusercontent.com/25906092/103399805-b5525880-4b7d-11eb-8b09-1c67910590ba.png)
![image](https://user-images.githubusercontent.com/25906092/103399810-bd11fd00-4b7d-11eb-9577-5351216ab0a0.png)
and when i running cv_camera_node, although the program shows fail to set image_width, but the resolution of the image data posted through the topic has been set correctly. That's confused me

**Comment by vigneshrajap** [comment]
In some OpenCV versions, API is like cv::CV_CAP_PROP_FRAME_WIDTH
