### ISSUE TITLE
[ERROR] [1623689901.478565848]: cv camera open failed: device_id0 cannot be opened

### ISSUE THREAD

**Issue by MAMorgado** [OTL/cv_camera#32]
Hi! 
I have a similar problem to issue #18.
I followed all your answers but unfortunately couldn't solve it.

I am using a Ricoh Theta Z1 camera. (ROS Noetic, Ubuntu 20.04)
I installed v4l2loopback, gstreamer1.0 packages and libuvc-theta + libuvc-theta-sample packages.

Although I can see the feed from the camera if I use gst_viewer without problems, i run into problems when I try to use your package cv_camera with it.

When I run ls /dev | grep video i get back video0. 

After I installed your package I tried to set up the camera device do use and run the node: 
rosparam set cv_camera/device_id 0
rosrun cv_camera cv_camera_node

I got this error instead
 WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1758) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Internal data stream error.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (888) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ WARN:0] global ../modules/videoio/src/cap_v4l.cpp (887) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR] [1623689901.478565848]: cv camera open failed: device_id0 cannot be opened

The results of running ls -l /dev/video* are crw-rw----+ 1 root video 81, 0 Jun 14 17:19 /dev/video0

I got nothing back when I ran sudo chmod 666 /dev/video* just like user lflanag4.

Can you give me a hand?

Best regards,

Mário

**Comment by OTL** [comment]
I have no idea. I think your debug is great.

**Comment by MAMorgado** [comment]
Hi OTL. It is working now. I think another program/camera was interfering with my v4l2loopback and crashing it before openCV could access the camera.  
I think you can close this issue. However I'm having another problem, since the image the cv_camera creates is very slow (especially after a few seconds). It appears to only be uploading a new image after more than a minute. It is also not the subsequent frame but another altogether. It almost seems like its not continuously streaming. Would you prefer me to open another issue?

**Comment by OTL** [comment]
Uhm, I'd like you to open another issue. The issues of this title are so many...
