### ISSUE TITLE
CMake find_package does not specify OpenCV version

### ISSUE THREAD

**Issue by mightyCelu** [OTL/cv_camera#6]
cv_camera depends on OpenCV2, however the find_package-call in the CMakeLists.txt will first discover OpenCV3 if both are installed. To circumvent this, the call should be changed to:
```
find_package(OpenCV 2 REQUIRED)
```
(see http://wiki.ros.org/vision_opencv)

**Comment by OTL** [comment]
Could you make PR?

**Comment by OTL** [comment]
thanks
